%%{init: {'theme':'dark'}}%%

sequenceDiagram
    actor User
    participant FE as Frontend
    participant BE as Backend
    participant DB as Database

    User ->> FE: Submits login form
    FE ->> BE: Sends request: POST /auth/login/
    BE ->> DB: Validates user data

    alt User data is valid
        DB -->> BE: Success
        BE ->> BE: Creates JWT token pair
        BE -->> FE: Sends access token in response, refresh token as httpOnly cookie
        FE -->> FE: Stores access token in localStorage
        FE -->> User: Redirects to dashboard
    else User data is invalid
        DB -->> BE: Failure
        BE -->> FE: Sends validation error
        FE -->> User: Displays validation errors
    end
