%%{init: {'theme':'dark'}}%%

sequenceDiagram
    participant FE as Frontend
    participant BE as Backend
    participant DB as Database

    FE ->> BE: Sends a request to private endpoint
    BE -->> FE: Returns 401
    FE ->> BE: Sends refresh request POST /auth/refresh/
    BE ->> BE: Validates refresh token

    alt Refresh token is expired or just invalid
        BE ->> DB: Deletes refresh token
        BE -->> FE: Returns 401
    else Refresh token is valid
        BE ->> DB: Deletes refresh token (blacklisting)
        BE ->> BE: Creates new token pair
        BE ->> DB: Saves new refresh token
        BE -->> FE: Returns refresh token in httpOnly and access token in response
    end
